name: resource-server

image:
  repository: adjodamawuli/resource-server
  tag: latest

service:
  port: 8080

springBoot:
  contextPath: /resource-server

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: adjoda.dev.com  # Remplacez par votre domaine
  tls:
    - hosts:
        - adjoda.dev.com
      secretName: adjoda-dev-com-tl