name: resource-server

replicaCount: 2

image:
  repository: adjodamawuli/resource-server
  tag: "latest"
  pullPolicy: IfNotPresent


#env:
#  - name: PORT
#    value: "8080"
#  - name: SERVER_SERVLET_CONTEXT_PATH
#    value: "resource-server"
service:
  type: LoadBalancer
  port: 8080

#service:
#  type: ClusterIP
#  port: 8080




ingress:
  enabled: false
  className: ""  # Optional: specify Ingress class name if required
  annotations: {}
  hosts:
    - host: adjoda-dev.esprit.tn  # Replace with your domain
      paths:
        - path: /resource-server
          pathType: ImplementationSpecific
  tls: []
