apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource-server.fullname" . }}
data:
  application.yml: |
    server:
      port: 8080

    spring:
      application:
        name: resource-server
