apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080  # Adjust if your application listens on a different port
      protocol: TCP
  selector:
    app: {{ .Values.name }}
